# Generated by Django 4.0 on 2022-02-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
