# Generated by Django 4.0 on 2022-03-04 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_line1', models.CharField(default='NULL', max_length=50)),
                ('Address_line2', models.CharField(default='NULL', max_length=50)),
                ('City', models.CharField(default='NULL', max_length=50)),
                ('State', models.CharField(default='NULL', max_length=50)),
                ('Phone_no', models.TextField(default='NULL', max_length=10)),
                ('Pincode', models.IntegerField()),
                ('landmark', models.CharField(default='NULL', max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
