# Generated by Django 4.0 on 2022-03-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemlist',
        ),
    ]
