# Generated by Django 4.0 on 2022-03-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_initial'),
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shippingdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.userdetails')),
            ],
        ),
    ]
