# Generated by Django 4.0 on 2022-03-06 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_initial'),
        ('home', '0004_shippingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetails',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userdetails'),
        ),
    ]
