# Generated by Django 4.0 on 2022-03-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='Item_No',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.itemlist'),
        ),
    ]
