# Generated by Django 4.0 on 2022-03-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_cartitems_item_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='Item_No',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='Item_No',
            field=models.ManyToManyField(to='home.itemlist'),
        ),
    ]
