# Generated by Django 4.0 on 2022-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_cartitems_item_no_cartitems_item_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='Item_No',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='Product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='Qty',
            field=models.IntegerField(default=0),
        ),
    ]
