# Generated by Django 4.0 on 2022-03-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_cartitems_item_no_cartitems_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='Product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='Qty',
            field=models.IntegerField(),
        ),
    ]
